#!/usr/bin/env python3
"""report_builder.py — Star Sec Auditor / Phase 8 (Final report assembly).

Merge per-finding Markdown files into a single, severity-ordered security report.
Each finding file is expected to start with an HTML-comment metadata block (see
templates/finding-template.md), e.g.:

    <!--
    id: WEB-001
    severity: High
    priority: P1
    confidence: Confirmed
    status: Open
    category: Broken Access Control (IDOR / BOLA)
    cwe: CWE-639
    owasp: A01:2021 / API1:2023
    -->

Missing or malformed metadata is tolerated — the builder falls back to sane
defaults so a partial report can always be produced.

Safety:
  * Read-only with respect to inputs and network-free.
  * Writes only the single output report you specify.

Usage:
  python report_builder.py --findings reports/findings/ --out reports/final-security-report.md
  python report_builder.py --findings reports/findings/ --summary reports/exec-summary.md \
                           --title "Security Audit — Acme App" --out reports/final-security-report.md
  python report_builder.py --help
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

SEVERITY_ORDER = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3, "Informational": 4}
PRIORITY_ORDER = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
DEFAULT_SEVERITY = "Informational"

META_BLOCK_RE = re.compile(r"<!--(.*?)-->", re.DOTALL)
KV_RE = re.compile(r"^\s*([A-Za-z_]+)\s*:\s*(.+?)\s*$")


def normalize_severity(value: str) -> str:
    v = (value or "").strip().capitalize()
    if v in SEVERITY_ORDER:
        return v
    # Accept a few synonyms.
    low = (value or "").strip().lower()
    mapping = {"crit": "Critical", "info": "Informational", "informational": "Informational"}
    return mapping.get(low, DEFAULT_SEVERITY)


def parse_finding(path: Path) -> dict:
    """Extract metadata + body from a finding markdown file. Never raises."""
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return {}

    meta: dict[str, str] = {}
    m = META_BLOCK_RE.search(text)
    if m:
        for line in m.group(1).splitlines():
            kv = KV_RE.match(line)
            if kv:
                meta[kv.group(1).strip().lower()] = kv.group(2).strip()

    # Strip the leading metadata comment(s) and any other HTML comments from the body
    # so the rendered report is clean, but keep the rest of the markdown verbatim.
    body = META_BLOCK_RE.sub("", text).strip()

    severity = normalize_severity(meta.get("severity", DEFAULT_SEVERITY))
    return {
        "file": path.name,
        "id": meta.get("id", path.stem),
        "severity": severity,
        "priority": (meta.get("priority", "") or "").upper(),
        "confidence": meta.get("confidence", ""),
        "status": meta.get("status", ""),
        "category": meta.get("category", ""),
        "cwe": meta.get("cwe", ""),
        "owasp": meta.get("owasp", ""),
        "body": body,
    }


def collect_findings(findings_dir: Path) -> list[dict]:
    files = sorted(findings_dir.glob("*.md"))
    findings = [f for f in (parse_finding(p) for p in files) if f]
    findings.sort(key=lambda f: (
        SEVERITY_ORDER.get(f["severity"], 99),
        PRIORITY_ORDER.get(f["priority"], 99),
        f["id"],
    ))
    return findings


def severity_table(findings: list[dict]) -> str:
    counts = {s: 0 for s in SEVERITY_ORDER}
    for f in findings:
        counts[f["severity"]] = counts.get(f["severity"], 0) + 1
    rows = "\n".join(f"| {sev} | {counts[sev]} |" for sev in SEVERITY_ORDER)
    return "| Severity | Count |\n|---|---|\n" + rows


def findings_index(findings: list[dict]) -> str:
    if not findings:
        return "_No findings recorded yet._"
    rows = ["| ID | Title | Severity | Priority | Confidence | Status |", "|---|---|---|---|---|---|"]
    for f in findings:
        title = first_heading(f["body"]) or f["id"]
        rows.append(
            f"| {f['id']} | {title} | {f['severity']} | {f['priority'] or '—'} | "
            f"{f['confidence'] or '—'} | {f['status'] or '—'} |"
        )
    return "\n".join(rows)


def first_heading(body: str) -> str:
    for line in body.splitlines():
        s = line.strip()
        if s.startswith("#"):
            return s.lstrip("#").strip()
    return ""


def build_report(title: str, summary_text: str | None, findings: list[dict]) -> str:
    today = date.today().isoformat()
    parts: list[str] = []
    parts.append(f"# {title}\n")
    parts.append(f"_Generated by Star Sec Auditor · {today}_\n")
    parts.append("> Authorized, defensive security audit. No audit proves the absence of vulnerabilities; "
                 "see Limitations.\n")

    parts.append("\n## Executive summary\n")
    parts.append(summary_text.strip() + "\n" if summary_text else
                 "_Add the executive summary here (or pass one with --summary)._\n")

    parts.append("\n## Findings overview\n")
    parts.append(severity_table(findings) + "\n")
    parts.append("\n### Findings index\n")
    parts.append(findings_index(findings) + "\n")

    parts.append("\n## Findings by severity\n")
    if not findings:
        parts.append("_No finding files were found in the input directory._\n")
    else:
        current = None
        for f in findings:
            if f["severity"] != current:
                current = f["severity"]
                parts.append(f"\n### {current}\n")
            parts.append("\n" + f["body"].strip() + "\n")
            parts.append("\n---\n")

    parts.append("\n## Limitations\n")
    parts.append(
        "- Snapshot-in-time, best-effort review of the provided code/commit; later changes are not covered.\n"
        "- Coverage is best-effort; some paths, generated code, vendored code, or binaries may be unreviewed.\n"
        "- Dynamic confirmation was limited to the authorized environment (or not performed).\n"
        "- Absence of a finding is not proof of absence of vulnerabilities.\n"
        "- Tool results depend on availability and rule coverage; unavailable tools are noted as `not available`.\n"
    )
    return "".join(parts)


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="report_builder.py",
        description="Star Sec Auditor — merge per-finding markdown files into a severity-ordered final report.",
        epilog="Tolerates partial data; safe to run early and re-run as findings firm up.",
    )
    p.add_argument("--findings", default="reports/findings",
                   help="Directory of per-finding .md files (default: reports/findings).")
    p.add_argument("--summary", default=None,
                   help="Optional path to an executive-summary markdown file to embed.")
    p.add_argument("--title", default="Security Audit Report", help="Report title.")
    p.add_argument("--out", default="reports/final-security-report.md",
                   help="Output report path (default: reports/final-security-report.md).")
    p.add_argument("--quiet", action="store_true", help="Suppress the summary on stderr.")
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    findings_dir = Path(args.findings)
    findings: list[dict] = []
    if findings_dir.is_dir():
        findings = collect_findings(findings_dir)
    else:
        print(f"[report_builder] Note: findings dir '{findings_dir}' not found — building an empty scaffold.",
              file=sys.stderr)

    summary_text = None
    if args.summary:
        sp = Path(args.summary)
        if sp.is_file():
            try:
                summary_text = sp.read_text(encoding="utf-8", errors="ignore")
            except OSError as exc:
                print(f"[report_builder] Warning: could not read summary '{sp}': {exc}", file=sys.stderr)
        else:
            print(f"[report_builder] Warning: summary file '{sp}' not found; continuing without it.", file=sys.stderr)

    report = build_report(args.title, summary_text, findings)

    out_path = Path(args.out)
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
    except OSError as exc:
        print(f"[report_builder] Error writing '{out_path}': {exc}", file=sys.stderr)
        return 1

    if not args.quiet:
        counts = {s: 0 for s in SEVERITY_ORDER}
        for f in findings:
            counts[f["severity"]] += 1
        print(f"[report_builder] Merged {len(findings)} finding(s) from {findings_dir}")
        print("[report_builder] " + "  ".join(f"{s}:{counts[s]}" for s in SEVERITY_ORDER))
        print(f"[report_builder] Wrote report: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
